# activate_venv.ps1
# generated by Claude by Ryan Deaton (rad53)

# this needs to run first Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

# Check if venv exists, create it if not
if (-Not (Test-Path "venv")) {
    Write-Host "Creating virtual environment..." -ForegroundColor Yellow
    python -m venv venv
    Write-Host "Installing dependencies..." -ForegroundColor Yellow
    .\venv\Scripts\pip install -r requirements.txt
} else {
    Write-Host "Virtual environment found." -ForegroundColor Green
}

# Activate
Write-Host "Activating virtual environment..." -ForegroundColor Yellow
.\venv\Scripts\Activate.ps1

Write-Host "Done! You are now in the venv." -ForegroundColor Green